# Generated by Django 5.2.5 on 2025-08-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_stripe_id_alter_customuser_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='stripe_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_stripe_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
